/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package banco;




/**
 *
 * @author Windows10
 */
public class NewJFrame extends javax.swing.JFrame {
    
    Banco banco = new Banco();
    
    String tipo;
    int numero;
    

    //int MAX = 10;
    //String temp = "a";
    
    public NewJFrame(){
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_cx1 = new javax.swing.JButton();
        btn_cx2 = new javax.swing.JButton();
        btn_cx3 = new javax.swing.JButton();
        btn_cx4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btn_normal = new javax.swing.JButton();
        btn_prio = new javax.swing.JButton();
        btn_rapido = new javax.swing.JButton();
        txtMostrarSenha = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt_Msenha = new javax.swing.JTextField();
        txt_caixa1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_cx1.setText("Caixa 1");
        btn_cx1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cx1ActionPerformed(evt);
            }
        });

        btn_cx2.setText("Caixa 2");
        btn_cx2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cx2ActionPerformed(evt);
            }
        });

        btn_cx3.setText("Caixa 3");
        btn_cx3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cx3ActionPerformed(evt);
            }
        });

        btn_cx4.setText("Caixa 4");
        btn_cx4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cx4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_cx1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cx2, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_cx3, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_cx4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cx1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cx2, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_cx3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cx4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btn_normal.setText("Comum");
        btn_normal.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_normal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_normalActionPerformed(evt);
            }
        });

        btn_prio.setText("Prioritário");
        btn_prio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_prioActionPerformed(evt);
            }
        });

        btn_rapido.setText("Rápido");
        btn_rapido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rapidoActionPerformed(evt);
            }
        });

        txtMostrarSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel2.setText("Sua Senha é :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btn_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn_prio, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btn_rapido, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMostrarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_normal, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_prio, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_rapido, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMostrarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txt_Msenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_Msenha.setText("Aguardando Chamada Senha");
        txt_Msenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_MsenhaActionPerformed(evt);
            }
        });

        txt_caixa1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt_caixa1.setText("Aguardando Chamada Caixa");
        txt_caixa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_caixa1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 81, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txt_Msenha, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(212, Short.MAX_VALUE)
                    .addComponent(txt_caixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(163, 163, 163)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(txt_Msenha, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(178, 178, 178)
                    .addComponent(txt_caixa1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(271, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_prioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_prioActionPerformed
        banco.numero++;
        banco.senhaTipo = "P - ";
        banco.listaSenha.add(banco.senhaTipo + banco.numero);
        txtMostrarSenha.setText("P - " + banco.numero);
        
    }//GEN-LAST:event_btn_prioActionPerformed

    private void btn_normalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_normalActionPerformed
        banco.numero++;
        banco.senhaTipo = "C - ";
        banco.listaSenha.add(banco.senhaTipo + banco.numero);  
        txtMostrarSenha.setText("C - " + banco.numero);
    }//GEN-LAST:event_btn_normalActionPerformed

    private void btn_rapidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rapidoActionPerformed
        banco.numero++;
        banco.senhaTipo = "R - ";
        banco.listaSenha.add(banco.senhaTipo + banco.numero);
        txtMostrarSenha.setText("R - " + banco.numero);
    }//GEN-LAST:event_btn_rapidoActionPerformed

    private void btn_cx1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cx1ActionPerformed
        txt_caixa1.setText("Caixa 1");
        if (banco.listaSenha.toString().contains("P - ")) {
            for (String fila : banco.listaSenha) {
                if (fila.contains("P - ")) {
                    txt_Msenha.setText(fila);
                    banco.listaSenha.remove(fila);
                    break;
                }
            }   
        }else{
            for (String fila : banco.listaSenha) {
                    txt_Msenha.setText(fila);
                    banco.listaSenha.remove(fila);
                    break;
            }
        }
        
    }//GEN-LAST:event_btn_cx1ActionPerformed

    private void btn_cx2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cx2ActionPerformed
        txt_caixa1.setText("Caixa 2");
        if (banco.listaSenha.toString().contains("R - ")) {
            for (String fila : banco.listaSenha) {
                if (fila.contains("R - ")) {
                    txt_Msenha.setText(fila);
                    banco.listaSenha.remove(fila);
                    break;
                }
            }   
        }else{
            for (String fila : banco.listaSenha) {
                    txt_Msenha.setText(fila);
                    banco.listaSenha.remove(fila);
                    break;
            }
        }
    }//GEN-LAST:event_btn_cx2ActionPerformed

    private void btn_cx3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cx3ActionPerformed
        txt_caixa1.setText("Caixa 3");
        if (banco.listaSenha.toString().contains("R - ")) {
            for (String fila : banco.listaSenha) {
                if (fila.contains("R - ")) {
                    txt_Msenha.setText(fila);
                    banco.listaSenha.remove(fila);
                    break;
                }
            }   
        }else{
            for (String fila : banco.listaSenha) {
                    txt_Msenha.setText(fila);
                    banco.listaSenha.remove(fila);
                    break;
            }
        }
    }//GEN-LAST:event_btn_cx3ActionPerformed

    private void btn_cx4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cx4ActionPerformed
       txt_caixa1.setText("Caixa 4");
       if (banco.listaSenha.toString().contains("C - ")) {
            for (String fila : banco.listaSenha) {
                if (fila.contains("C - ")) {
                    txt_Msenha.setText(fila);
                    banco.listaSenha.remove(fila);
                    break;
                }
            }   
        }else{
            for (String fila : banco.listaSenha) {
                    txt_Msenha.setText(fila);
                    banco.listaSenha.remove(fila);
                    break;
            }
        }
    }//GEN-LAST:event_btn_cx4ActionPerformed

    private void txt_MsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_MsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_MsenhaActionPerformed

    private void txt_caixa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_caixa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_caixa1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cx1;
    private javax.swing.JButton btn_cx2;
    private javax.swing.JButton btn_cx3;
    private javax.swing.JButton btn_cx4;
    private javax.swing.JButton btn_normal;
    private javax.swing.JButton btn_prio;
    private javax.swing.JButton btn_rapido;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtMostrarSenha;
    private javax.swing.JTextField txt_Msenha;
    private javax.swing.JTextField txt_caixa1;
    // End of variables declaration//GEN-END:variables
}
